// Generated by CoffeeScript 1.6.3
define(['Dropbox', 'eventmgr'], function(Dropbox, eventManager) {
  var DropboxProvider, client, datastoreManager;
  client = new Dropbox.Client({
    key: 't35la3qyv5bvtry'
  });
  client.authDriver(new Dropbox.AuthDriver.Popup({
    receiverUrl: "http://localhost:4000/dropbox-oauth-receiver.html",
    rememberUser: true
  }));
  client.authenticate({
    interactive: false
  }, function(error) {
    if (error) {
      return alert('Authentication error: ' + error);
    }
  });
  if (client.isAuthenticated()) {
    console.log('b');
    eventManager.trigger('remotesync');
    datastoreManager = client.getDatastoreManager();
    datastoreManager.openDefaultDatastore(function(error, datastore) {
      var results, taskTable;
      if (error) {
        console.log('Error opening default datastore: ' + error);
      }
      taskTable = datastore.getTable('metaData');
      return results = taskTable.get('1');
    });
  }
  return DropboxProvider = (function() {
    function DropboxProvider() {}

    DropboxProvider.client = client;

    DropboxProvider.datastoreManager = datastoreManager;

    return DropboxProvider;

  })();
});
