// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
  var EventManager, eventManager, pendingList, ready;
  eventManager = new (EventManager = (function() {
    function EventManager() {}

    EventManager.prototype.triggerEvent = void 0;

    EventManager.prototype.startTrigger = function(event, time) {
      var triggerEvent,
        _this = this;
      return triggerEvent = setInterval(function() {
        return _this.trigger(event);
      }, time);
    };

    EventManager.prototype.stopTrigger = function() {
      return clearInterval(triggerEvent);
    };

    return EventManager;

  })());
  _.extend(eventManager, Backbone.Events);
  $(window).on('online', function() {
    return eventManager.trigger('online');
  });
  $(window).on('offline', function() {
    return eventManager.trigger('offline');
  });
  pendingList = ['metaready', 'reccntrsready'];
  ready = function(event) {
    pendingList = _.reject(pendingList, function(pendingEvent) {
      return pendingEvent === event;
    });
    if (pendingList.length === 0) {
      return eventManager.trigger('appready');
    }
  };
  eventManager.on('metaready', function() {
    return ready('metaready');
  });
  eventManager.on('reccntrsready', function() {
    return ready('reccntrsready');
  });
  return eventManager;
});
