// Generated by CoffeeScript 1.6.3
define(['underscore', 'backbone'], function(_, Backbone) {
  var EventManager, eventManager;
  eventManager = new (EventManager = (function() {
    function EventManager() {}

    return EventManager;

  })());
  _.extend(eventManager, Backbone.Events);
  $(window).on('online', function() {
    return eventManager.trigger('online');
  });
  $(window).on('offline', function() {
    return eventManager.trigger('offline');
  });
  return eventManager;
});
