// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone', 'models/record', 'collections/records', 'views/record'], function($, _, Backbone, Record, Records, RecordView) {
  'use strict';
  return Backbone.View.extend({
    el: '#app',
    events: {
      'click #add-record': 'addRecord'
    },
    initialize: function() {
      this.$recordsView = this.$('records');
      return this.records = new Records;
    },
    render: function() {
      return this;
    },
    addRecord: function() {
      var recordView;
      recordView = new RecordView({
        model: new Record
      });
      return this.$recordsView.append(recordView.render().el);
    },
    addAll: function() {}
  });
});
