// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone', 'collections/posts', 'text!templates/index/bar.html'], function($, _, Backbone, posts, bar) {
  'use strict';
  return Backbone.View.extend({
    tagName: 'div',
    id: 'index_content',
    className: 'inner',
    indexBarTemplate: _.template(bar),
    initialize: function() {
      return posts.on('reset', this.renderIndex, this);
    },
    renderIndex: function() {
      var _this = this;
      this.$el.empty();
      return posts.each(function(post) {
        bar = $($.parseHTML(_this.indexBarTemplate({
          title: post.get('title'),
          link: post.getLink(),
          time: post.getTime().toLocaleDateString()
        }))[0]);
        _.each(post.getTags(), function(tag) {
          return bar.append(_this.options.tagLinkTemplate({
            name: tag,
            link: '#/tags/' + tag
          }));
        });
        return _this.$el.append(bar);
      });
    }
  });
});
