// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone', 'collections/posts', 'routers/router', 'text!templates/main/switcher.html'], function($, _, Backbone, posts, router, switcher) {
  'use strict';
  return Backbone.View.extend({
    events: {
      'click #page-switcher-pre': 'preSwitch',
      'click #page-switcher-next': 'nextSwitch'
    },
    switcherTemplate: _.template(switcher),
    initialize: function() {
      this.$el.append(this.switcherTemplate({
        location: 'left',
        content: '‹',
        id: 'pre'
      }));
      this.$el.append(this.switcherTemplate({
        location: 'right',
        content: '›',
        id: 'next'
      }));
      this.$el.append('<section class="inner" id="main_content" />');
      this.$preSwitcher = this.$('#page-switcher-pre');
      this.$nextSwitcher = this.$('#page-switcher-next');
      this.$content = this.$('#main_content');
      return posts.on('contentChange', this.contentRender, this);
    },
    render: function() {
      this.$preSwitcher.toggle(!!posts.offsetPost(-1));
      this.$nextSwitcher.toggle(!!posts.offsetPost(1));
      return this;
    },
    contentRender: function(content) {
      return this.$content.html(content);
    },
    preSwitch: function() {
      return router.navigate('//posts/' + posts.offsetPost(-1).get('id'));
    },
    nextSwitch: function() {
      return router.navigate('//posts/' + posts.offsetPost(1).get('id'));
    }
  });
});
