// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone', 'models/record'], function($, _, Backbone, Record) {
  'use strict';
  return Backbone.View.extend({
    tagName: 'tr',
    indexBarTemplate: _.template("<td><%= catgroyName() || '-' %></td><td><%= name || '-'  %></td><td><%= worker || '-'  %></td><td><%= num || '-' %> <%= catgroy == 1 ? '桶' : '元' %></td>"),
    render: function() {
      return this;
    }
  });
});
