// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
  'use strict';
  return Backbone.Model.extend({
    url: '/posts',
    getHtml: function(callback) {
      var _this = this;
      return $.get(this.get('uri'), function(context) {
        _this.htmlContent = context;
        return callback.call(_this);
      });
    },
    getLink: function() {
      return '#/posts/' + this.get('id');
    },
    getTags: function() {
      if (!this.get('tags')) {
        return [];
      } else {
        return this.get('tags').split(',');
      }
    },
    getTime: function() {
      return new Date(this.get('date'));
    }
  });
});
