// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone', 'common', 'dropboxprovider'], function($, _, Backbone, common, DropboxProvider) {
  'use strict';
  return Backbone.Model.extend({
    defaults: function() {
      return {
        createTime: new Date,
        modifyTime: new Date,
        contentTime: void 0,
        content: []
      };
    },
    remote: {
      table: 'recordContainers',
      key: 'contentTime'
    },
    toRemoteFormat: function() {
      var recCntr;
      recCntr = this.toJSON();
      recCntr.content = JSON.stringify(recCntr.content);
      delete recCntr.id;
      return recCntr;
    },
    toLocalFormat: function(recCntr) {
      recCntr.content = JSON.parse(recCntr.content);
      return recCntr;
    }
  });
});
