// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
  'use strict';
  return Backbone.Model.extend({
    defaults: function() {
      return {
        createTime: new Date,
        lastModifyTime: new Date,
        lastSyncTime: void 0,
        contentTime: void 0,
        content: []
      };
    },
    toRemoteFormat: function() {
      var recCntr;
      recCntr = this.toJSON();
      recCntr.content = JSON.stringify(recCntr.content);
      return recCntr;
    }
  });
});
