// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone', 'common'], function($, _, Backbone, Common) {
  'use strict';
  return Backbone.Model.extend({
    categoryName: function() {
      return (_.findWhere(Common.categories, {
        value: this.get('catgroy') || {}
      })).name;
    }
  });
});
