// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone', 'moment', 'common'], function($, _, Backbone, moment, Common) {
  'use strict';
  return Backbone.Model.extend({
    defaults: {
      worker: 0,
      createTime: new Date
    },
    categoryName: function() {
      return (Common.getCategory(this.get('category')) || {}).text;
    },
    detailName: function() {
      return (Common.getDetail(this.get('category'), this.get('detail')) || {}).text;
    },
    workerName: function() {
      return (Common.getWorker(this.get('worker')) || {}).text;
    },
    isValid: function() {
      return this.get('num') && (Common.getDetail(this.get('category'), this.get('detail')).value !== void 0);
    },
    isActived: function() {
      return moment(this.get('createTime')).startOf('day').isSame(moment().startOf('day'));
    }
  });
});
