// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone', 'moment', 'common'], function($, _, Backbone, moment, Common) {
  'use strict';
  return Backbone.Model.extend({
    defaults: function() {
      return {
        worker: 0,
        createTime: Common.targetDate.date
      };
    },
    categoryName: function() {
      return (Common.getCategory(this.get('category')) || {}).text;
    },
    detailName: function() {
      return (Common.getDetail(this.get('category'), this.get('detail')) || {}).text;
    },
    workerName: function() {
      return (Common.getWorker(this.get('worker')) || {}).text;
    },
    detailEditable: function() {
      return !_.isUndefined(this.get("category"));
    },
    isValid: function() {
      return this.get('num') && !_.isUndefined(Common.getDetail(this.get('category'), this.get('detail')));
    },
    isActived: function() {
      return moment(this.get('createTime')).startOf('day').isSame(moment(Common.targetDate.date).startOf('day'));
    }
  });
});
