// Generated by CoffeeScript 1.6.3
define(['underscore', 'backbone', 'models/record', 'common'], function(_, Backbone, Record, Common) {
  'use strict';
  return Backbone.Collection.extend({
    model: Record
  });
});
