// Generated by CoffeeScript 1.6.3
define(['underscore', 'backbone', 'models/record', 'store', 'common'], function(_, Backbone, Record, Store, Common) {
  'use strict';
  return Backbone.Collection.extend({
    model: Record,
    localStorage: new Store('Records'),
    initialize: function() {
      var _this = this;
      this.listenTo(Common.targetDate, 'change', function() {
        return _this.trigger('filter');
      });
      return this;
    }
  });
});
