// Generated by CoffeeScript 1.6.3
define(['underscore', 'backbone', 'models/record', 'store'], function(_, Backbone, Record, Store) {
  'use strict';
  return Backbone.Collection.extend({
    model: Record,
    localStorage: new Store('Records')
  });
});
